# Generated by Django 3.1.4 on 2021-01-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('descr', models.CharField(max_length=300)),
                ('total_ticket', models.IntegerField(default=50)),
                ('available_ticket', models.IntegerField(default=50)),
                ('imageurl', models.URLField(max_length=300)),
                ('country', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=2010)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
